
// Definindo valores para as IDs

//---------------------------------------------------------------------------------------------------

#define ID_RPGICON 100

#define ID_COMPRA 200
#define ID_VENDA 201
#define ID_SAIR 202
#define ID_RETORNO 203
#define ID_REALIZACOMPRA 204
#define ID_REALIZAVENDA 205

#define ID_ARMAS 206
#define ID_ESCUDO 207
#define ID_ELMO 208
#define ID_ARMADURA 209
#define ID_ACESSORIO 210
#define ID_CONSUMO 211
#define ID_BOLSA 212

#define ID_BUTTONCOMPRA 300
#define ID_BUTTONVENDA 301
#define ID_BUTTONSAIR 302

#define ID_BUTTONREALIZACOMPRA 303
#define ID_BUTTONREALIZAVENDA 304

#define ID_BUTTONRETORNO 305

#define ID_BUTTONARMAS 306
#define ID_BUTTONESCUDO 307
#define ID_BUTTONELMO 308
#define ID_BUTTONARMADURA 309
#define ID_BUTTONACESSORIO 310
#define ID_BUTTONCONSUMO 311
#define ID_BUTTONBOLSA 312

#define ID_LISTA 400
#define ID_INVENTARIO 401
#define ID_LBOLSA 402

#define ID_ARMA_SHORTSWORD 500
#define ID_ARMA_BARONG 501
#define ID_ARMA_RONDELLDAGGER 502
#define ID_ARMA_JAMBIYA 503
#define ID_ARMA_CURESTAFF 504
#define ID_ARMA_PURESTAFF 505
#define ID_ARMA_FORCEROD 506
#define ID_ARMA_SLEETROD 507
#define ID_ARMA_LONGBOW 508
#define ID_ARMA_MITHRILBOW 509

#define ID_ESCUDO_ROUNDSHIELD 510
#define ID_ESCUDO_OPALSHIELD 511
#define ID_ESCUDO_FLAMESHIELD 512
#define ID_ESCUDO_REVERIESHIELD 513
#define ID_ESCUDO_SACRISHIELD 514

#define ID_ELMO_IRONHELM 515
#define ID_ELMO_CIRCLET 516
#define ID_ELMO_FEATHER 517
#define ID_ELMO_BERETTE 518
#define ID_ELMO_HEADBAND 519

#define ID_ARMADURA_DIAMONDARMOR 520
#define ID_ARMADURA_MIRAGEVEST 521
#define ID_ARMADURA_LIGHTROBE 522
#define ID_ARMADURA_DARKROBE 523
#define ID_ARMADURA_PEYTRAL 524

#define ID_ACESSORIO_BATTLEBOOTS 525
#define ID_ACESSORIO_SPARKBOOTS 526
#define ID_ACESSORIO_MAGICRING 527
#define ID_ACESSORIO_SCARAB 528
#define ID_ACESSORIO_FAIRYSHOES 529

#define ID_CONSUMO_HEALTHPOTION 530
#define ID_CONSUMO_MANAPOTION 531
#define ID_CONSUMO_ANTIDOTE 532
#define ID_CONSUMO_SOFT 533
#define ID_CONSUMO_ELIXIR 534

#define ID_BOLSA_BOLSA 535
#define ID_BOLSA_BAU 536

